// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Configuration;
using tn_prueba_web.Shared.Models;

#nullable disable

namespace tn_prueba_web.Server.Data
{
    public partial class tn_pruebaContext : DbContext
    {
        public tn_pruebaContext()
        {
        }

        public tn_pruebaContext(DbContextOptions<tn_pruebaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CliCliente> CliClientes { get; set; }
        public virtual DbSet<EstrEstadoRe> EstrEstadoRes { get; set; }
        public virtual DbSet<PaqPaquete> PaqPaquetes { get; set; }
        public virtual DbSet<ResReserva> ResReservas { get; set; }
        public virtual DbSet<SerServicio> SerServicios { get; set; }
        public virtual DbSet<TpaqTipoPaquete> TpaqTipoPaquetes { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            IConfigurationRoot configuration = new ConfigurationBuilder()
                        .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                        .AddJsonFile("appsettings.json")
                        .Build();
            optionsBuilder.UseSqlServer(configuration.GetConnectionString("DefaultConnection"));
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.Entity<CliCliente>(entity =>
            {
                entity.HasKey(e => e.CliCodigo)
                    .HasName("PK__cli_clie__9C28A2458C586DAD");

                entity.Property(e => e.CliFechaRegistro).HasDefaultValueSql("(getdate())");
            });

            modelBuilder.Entity<EstrEstadoRe>(entity =>
            {
                entity.HasKey(e => e.EstrCodigo)
                    .HasName("PK__estr_est__05D5E62B0B233EE0");
            });

            modelBuilder.Entity<PaqPaquete>(entity =>
            {
                entity.HasKey(e => e.PaqCodigo)
                    .HasName("PK__paq_paqu__2F0F42B88A4E8EBF");

                entity.Property(e => e.PaqFechaRegistro).HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.PaqCodtpaqNavigation)
                    .WithMany(p => p.PaqPaquetes)
                    .HasForeignKey(d => d.PaqCodtpaq)
                    .HasConstraintName("FK__paq_paque__paq_c__3C69FB99");
            });

            modelBuilder.Entity<ResReserva>(entity =>
            {
                entity.HasKey(e => e.ResCodigo)
                    .HasName("PK__res_rese__1AB8C5EDADC609CB");

                entity.Property(e => e.ResFechaRegistro).HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.ResCodcliNavigation)
                    .WithMany(p => p.ResReservas)
                    .HasForeignKey(d => d.ResCodcli)
                    .HasConstraintName("FK__res_reser__res_c__6A30C649");

                entity.HasOne(d => d.ResCodestrNavigation)
                    .WithMany(p => p.ResReservas)
                    .HasForeignKey(d => d.ResCodestr)
                    .HasConstraintName("FK__res_reser__res_c__6C190EBB");

                entity.HasOne(d => d.ResCodserNavigation)
                    .WithMany(p => p.ResReservas)
                    .HasForeignKey(d => d.ResCodser)
                    .HasConstraintName("FK__res_reser__res_c__6B24EA82");
            });

            modelBuilder.Entity<SerServicio>(entity =>
            {
                entity.HasKey(e => e.SerCodigo)
                    .HasName("PK__ser_serv__2EBEDD9507060A91");

                entity.HasOne(d => d.SerCodpaqNavigation)
                    .WithMany(p => p.SerServicios)
                    .HasForeignKey(d => d.SerCodpaq)
                    .HasConstraintName("FK__ser_servi__ser_c__6754599E");
            });

            modelBuilder.Entity<TpaqTipoPaquete>(entity =>
            {
                entity.HasKey(e => e.TpaqCodigo)
                    .HasName("PK__tpaq_tip__D34B47FC82CABCFF");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}