// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace tn_prueba_web.Shared.Models
{
    [Table("paq_paquete")]
    public partial class PaqPaquete
    {
        public PaqPaquete()
        {
            SerServicios = new HashSet<SerServicio>();
        }

        [Key]
        [Column("paq_codigo")]
        public int PaqCodigo { get; set; }
        [Column("paq_nombre")]
        [StringLength(200)]
        public string PaqNombre { get; set; }
        [Column("paq_descripcion")]
        [StringLength(500)]
        public string PaqDescripcion { get; set; }
        [Column("paq_direccion")]
        [StringLength(500)]
        public string PaqDireccion { get; set; }
        [Column("paq_imagen")]
        [StringLength(50)]
        public string PaqImagen { get; set; }
        [Column("paq_codtpaq")]
        public int? PaqCodtpaq { get; set; }
        [Column("paq_fecha_registro", TypeName = "datetime")]
        public DateTime? PaqFechaRegistro { get; set; }

        [ForeignKey(nameof(PaqCodtpaq))]
        [InverseProperty(nameof(TpaqTipoPaquete.PaqPaquetes))]
        public virtual TpaqTipoPaquete PaqCodtpaqNavigation { get; set; }
        [InverseProperty(nameof(SerServicio.SerCodpaqNavigation))]
        public virtual ICollection<SerServicio> SerServicios { get; set; }
    }
}