// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace tn_prueba_web.Shared.Models
{
    [Table("res_reserva")]
    public partial class ResReserva
    {
        [Key]
        [Column("res_codigo")]
        public int ResCodigo { get; set; }
        [Column("res_codcli")]
        public int? ResCodcli { get; set; }
        [Column("res_codser")]
        public int? ResCodser { get; set; }
        [Column("res_fecha", TypeName = "datetime")]
        public DateTime? ResFecha { get; set; }
        [Column("res_codestr")]
        public int? ResCodestr { get; set; }
        [Column("res_fecha_registro", TypeName = "datetime")]
        public DateTime? ResFechaRegistro { get; set; }

        [ForeignKey(nameof(ResCodcli))]
        [InverseProperty(nameof(CliCliente.ResReservas))]
        public virtual CliCliente ResCodcliNavigation { get; set; }
        [ForeignKey(nameof(ResCodestr))]
        [InverseProperty(nameof(EstrEstadoRe.ResReservas))]
        public virtual EstrEstadoRe ResCodestrNavigation { get; set; }
        [ForeignKey(nameof(ResCodser))]
        [InverseProperty(nameof(SerServicio.ResReservas))]
        public virtual SerServicio ResCodserNavigation { get; set; }
    }
}