// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace tn_prueba_web.Shared.Models
{
    [Table("ser_servicio")]
    public partial class SerServicio
    {
        public SerServicio()
        {
            ResReservas = new HashSet<ResReserva>();
        }

        [Key]
        [Column("ser_codigo")]
        public int SerCodigo { get; set; }
        [Column("ser_nombre")]
        [StringLength(200)]
        public string SerNombre { get; set; }
        [Column("ser_precio")]
        public double? SerPrecio { get; set; }
        [Column("ser_descripcion")]
        [StringLength(500)]
        public string SerDescripcion { get; set; }
        [Column("ser_imagen")]
        [StringLength(50)]
        public string SerImagen { get; set; }
        [Column("ser_codpaq")]
        public int? SerCodpaq { get; set; }

        [ForeignKey(nameof(SerCodpaq))]
        [InverseProperty(nameof(PaqPaquete.SerServicios))]
        public virtual PaqPaquete SerCodpaqNavigation { get; set; }
        [InverseProperty(nameof(ResReserva.ResCodserNavigation))]
        public virtual ICollection<ResReserva> ResReservas { get; set; }
    }
}