// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace tn_prueba_web.Shared.Models
{
    [Table("tpaq_tipo_paquete")]
    public partial class TpaqTipoPaquete
    {
        public TpaqTipoPaquete()
        {
            PaqPaquetes = new HashSet<PaqPaquete>();
        }

        [Key]
        [Column("tpaq_codigo")]
        public int TpaqCodigo { get; set; }
        [Column("tpaq_nombre")]
        [StringLength(50)]
        public string TpaqNombre { get; set; }
        [Column("tpaq_descripcion")]
        [StringLength(100)]
        public string TpaqDescripcion { get; set; }

        [InverseProperty(nameof(PaqPaquete.PaqCodtpaqNavigation))]
        public virtual ICollection<PaqPaquete> PaqPaquetes { get; set; }
    }
}